manifest:
  remotes:
    - name: zmkfirmware
      url-base: https://github.com/zmkfirmware
  projects:
    - name: zmk
      remote: zmkfirmware
      revision: f84ef436cd8e88f9d1580a9b86bab2fae8d349c6
      import: app/west.yml
  self:
    path: config
